name: ROOT 6.30

on:
  schedule:
    - cron: '40 1 * * *'

    jobs:
  call-workflow-passing-data:
    uses: root-project/root/.github/workflows/root-ci.yaml
    with:
      head_ref: v6-30-00-patches
      base_ref: v6-30-00-patches